version: "3"

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list-all

  build:
    desc: Build the provider binary
    cmds:
      - go build -o terraform-provider-technitium-dns-server

  package:
    desc: Build and package provider for dev_overrides usage
    deps: [build]
    cmds:
      - echo "Building provider for dev_overrides..."
      - mkdir -p dist
      - cp terraform-provider-technitium-dns-server dist/terraform-provider-technitium-dns-server
      - echo "âœ… Provider packaged in dist/ directory"
      # - echo "ðŸ“ Binary: dist/terraform-provider-technitium-dns-server"
      # - echo "ðŸ”§ Dev override path: {{.PWD}}/dist"
      - echo ""
      - echo "Add this to your ~/.terraformrc:"
      - echo 'provider_installation {'
      - echo '  dev_overrides {'
      - echo '    "local/kusold/technitium-dns-server" = "{{.PWD}}/dist"'
      - echo '  }'
      - echo '  direct {}'
      - echo '}'

  test:
    desc: Run all tests
    cmds:
      - go test -v ./...

  test-unit:
    desc: Run unit tests only (short)
    cmds:
      - go test -v -short ./...

  test-acc:
    desc: Run acceptance tests
    env:
      TF_ACC: "1"
    cmds:
      - go test -v ./... -timeout=30m

  test-parallel:
    desc: Run tests in parallel
    cmds:
      - go test -v -parallel=4 ./...

  clean:
    desc: Clean build artifacts and caches
    cmds:
      - rm -f terraform-provider-technitium-dns-server
      - go clean -cache
      - go clean -testcache

  lint:
    desc: Run linter
    cmds:
      - golangci-lint run

  fmt:
    desc: Format code
    cmds:
      - go fmt ./...

  fmt-imports:
    desc: Format code and organize imports
    cmds:
      - goimports -local github.com/kusold/terraform-provider-technitium-dns-server -w .

  pre-commit:install:
    desc: Install pre-commit hooks
    cmds:
      - pre-commit install
      - pre-commit install --hook-type pre-push
      - echo "âœ… Pre-commit hooks installed successfully"

  pre-commit:run:
    desc: Run pre-commit hooks on all files
    cmds:
      - pre-commit run --all-files

  pre-commit:update:
    desc: Update pre-commit hooks to latest versions
    cmds:
      - pre-commit autoupdate

  docs:
    desc: Generate documentation using tfplugindocs (matches GitHub Action)
    deps: [build]
    cmds:
      - echo "Generating Terraform provider documentation..."
      - |
        if ! command -v tfplugindocs &> /dev/null; then
          echo "Installing tfplugindocs..."
          go install github.com/hashicorp/terraform-plugin-docs/cmd/tfplugindocs@latest
        fi
      - tfplugindocs generate --provider-name technitium
      - echo "âœ… Documentation generated successfully!"

  install:
    desc: Install provider locally for testing
    deps: [build]
    cmds:
      - mkdir -p ~/.terraform.d/plugins/kusold.dev/dev/technitium-dns-server/0.1.0/darwin_amd64/
      - cp terraform-provider-technitium-dns-server ~/.terraform.d/plugins/kusold.dev/dev/technitium-dns-server/0.1.0/darwin_amd64/

  dev-setup:
    desc: Set up development environment
    cmds:
      - echo "Setting up development environment..."
      - direnv allow
      - go mod download
      - task: pre-commit:install
      - echo "Development environment ready!"

  dev-test-container:
    desc: Start test Technitium container
    cmds:
      - echo "Starting test Technitium container..."
      - |
        docker run -d --name technitium-test \
          -p 5380:5380 \
          -e DNS_SERVER_ADMIN_PASSWORD=admin \
          technitium/dns-server:13.6.0
      - echo "Container started. Wait a few seconds for it to initialize..."
      - sleep 10
      - echo "Test container ready at http://localhost:5380"

  dev-stop-container:
    desc: Stop test container
    cmds:
      - echo "Stopping test container..."
      - docker stop technitium-test || true
      - docker rm technitium-test || true
      - echo "Test container stopped."

  fetch-ai-docs:
    desc: Fetch important documentation for AI to reference
    cmds:
      - mkdir -p .ai/docs
      - curl -s https://raw.githubusercontent.com/hashicorp/web-unified-docs/refs/heads/main/content/terraform-docs-common/docs/plugin/best-practices/hashicorp-provider-design-principles.mdx -o .ai/docs/hashicorp-provider-design-principles.mdx
      - curl -s https://raw.githubusercontent.com/TechnitiumSoftware/DnsServer/refs/heads/master/APIDOCS.md -o .ai/docs/technitium-api.md
      - bin/split_technitium_api.sh
      - rm .ai/docs/technitium-api.md
