name: Generate Documentation

on:
  push:
    branches: [ main ]
    paths:
      - 'internal/provider/**'
      - 'examples/**'
      - 'templates/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'internal/provider/**'
      - 'examples/**'
      - 'templates/**'

jobs:
  docs:
    name: Generate Documentation
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - name: Setup Go
        uses: actions/setup-go@19bb51245e9c80abacb2e91cc42b33fa478b8639 # v4
        with:
          go-version-file: 'go.mod'
          cache: true

      - name: Generate docs
        run: |
          go install github.com/hashicorp/terraform-plugin-docs/cmd/tfplugindocs@latest
          tfplugindocs generate --provider-name technitium

      - name: Check for changes
        id: verify-changed-files
        run: |
          if [ -n "$(git status --porcelain docs/)" ]; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Commit updated docs
        if: steps.verify-changed-files.outputs.changed == 'true' && github.event_name == 'push'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add docs/
          git commit -m "docs: auto-generate provider documentation" || exit 0
          git push

      - name: Comment on PR if docs changed
        if: steps.verify-changed-files.outputs.changed == 'true' && github.event_name == 'pull_request'
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '📝 Provider documentation has been updated. Please review the changes in the `docs/` directory.'
            })
