name: Renovate
on:
  schedule:
    # Run Renovate on Mondays at 6 AM UTC
    - cron: '0 6 * * 1'
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: false
        default: 'info'
        type: choice
        options:
          - debug
          - info
          - warn
          - error

jobs:
  renovate:
    name: Renovate Dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v43.0.8
        with:
          configurationFile: renovate.json
          token: ${{ secrets.RENOVATE_TOKEN || secrets.GITHUB_TOKEN }}
        env:
          LOG_LEVEL: ${{ inputs.logLevel || 'info' }}
          RENOVATE_REPOSITORIES: ${{ github.repository }}
          RENOVATE_USERNAME: ${{ github.repository_owner }}
          RENOVATE_GIT_AUTHOR: 'Renovate Bot <bot@renovateapp.com>'
